/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "All About Salesforce Marketing Cloud",
  "tagline": "Excellence as duty",
  "favicon": "img/favicon.ico",
  "url": "https://arthurbackouche.github.io",
  "baseUrl": "/",
  "organizationName": "arthurbackouche",
  "projectName": "arthurbackouche",
  "deploymentBranch": "gh-pages",
  "trailingSlash": false,
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/Users/arthurbackouche/My Webiste/arthurbackouche/sidebars.js",
          "editUrl": "https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/"
        },
        "blog": {
          "showReadingTime": true,
          "editUrl": "https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/"
        },
        "theme": {
          "customCss": "/Users/arthurbackouche/My Webiste/arthurbackouche/src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/docusaurus-social-card.jpg",
    "navbar": {
      "logo": {
        "alt": "My Site Logo",
        "src": "img/logo.svg"
      },
      "items": [
        {
          "type": "doc",
          "docId": "/category/ssjs",
          "position": "left",
          "label": "SSJS"
        },
        {
          "type": "doc",
          "docId": "/category/ampscript",
          "position": "left",
          "label": "AMPScript"
        },
        {
          "type": "doc",
          "docId": "/category/sfmc-sql",
          "position": "left",
          "label": "SFMC SQL"
        },
        {
          "type": "doc",
          "docId": "/category/sfmc-config",
          "position": "left",
          "label": "SFMC Config"
        },
        {
          "to": "/blog",
          "label": "Blog",
          "position": "left"
        },
        {
          "href": "https://www.linkedin.com/in/arthurbackouche/",
          "label": "LinkedIn",
          "position": "right"
        },
        {
          "href": "https://trailblazer.me/id/arthurbackouche",
          "label": "Salesforce",
          "position": "right"
        },
        {
          "href": "https://github.com/arthurbackouche",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "SSJS",
              "to": "/docs/category/ssjs"
            },
            {
              "label": "AMPScript",
              "to": "/docs/category/AMPScript"
            },
            {
              "label": "SFMC SQL",
              "to": "/docs/category/sfmc-sql"
            },
            {
              "label": "SFMC Config",
              "to": "/docs/category/sfmc-config"
            }
          ]
        },
        {
          "title": "My Socials",
          "items": [
            {
              "label": "LinkedIn",
              "href": "https://www.linkedin.com/in/arthurbackouche/"
            },
            {
              "label": "Youtube",
              "href": "https://www.youtube.com/channel/UCHPcmgOhmdf0O691uWJImAA"
            },
            {
              "label": "Instagram",
              "href": "https://www.instagram.com/arthurbackouche/"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/arthurbackouche"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Trailhead",
              "href": "https://trailblazer.me/id/arthurbackouche"
            },
            {
              "label": "StackExchange",
              "href": "https://salesforce.stackexchange.com/users/121938/arthur-backouche"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/arthurbackouche"
            },
            {
              "label": "ProductHunt",
              "href": "https://www.producthunt.com/@arthurbackouche"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2023 Arthur Backouche."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
